name: Sudokuz

on: push

env:
  PYTHON_VERSION: 3.12

jobs:
  # Linting job
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # Install ruff
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      # Perform ruff checks
      - name: Linting with ruff
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          ruff check src/
          ruff format --check src/

  # Building job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # Install ruff
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install hatchling
      # Build with hatchling
      - name: Build dist
        run: |
          python -m build
      # Archive the build
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: sudokuz-build
          path: dist/*
